#
# trainingInput:
#   scaleTier: CUSTOM
#   masterType: n1-highmem-2
#   runtimeVersion: '2.1'
#   pythonVersion: '3.7'


trainingInput:
  scaleTier: BASIC
  runtimeVersion: '2.1'
  pythonVersion: '3.7'
