language: python

python:
  - 3.6

before_install:
  - echo "Upgrading pip"
  - python3 -m pip install --upgrade pip
  - echo "Python Version"
  - python3 --version
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

    # - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

  # - "export PYTHONPATH=${PYTHONPATH}:/   $(pwd)"
  #
  #  export PYTHONPATH="${PYTHONPATH}:/my/other/path"

  - echo "Travis CI Dir $TRAVIS_BUILD_DIR"

install:
  - echo "Install project dependancies and requirements"
  - pip3 install codecov
  - pip3 install -r requirements.txt
  - pip3 install pytest

script:
  - cd psp
  - echo "Travis CI Dir $TRAVIS_BUILD_DIR"
  - echo "Running dataset tests"
  - python3 -m tests.test_datasets.py
  - echo "Running model tests"
  # - python3 -m psp.tests.test_models.py

after_success:
  - codecov
  - echo "Build success"
