trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_m
  workerType: complex_model_m
  parameterServerType: large_model
  workerCount: 9
  parameterServerCount: 3
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: score[1]
    maxTrials: 30
    maxParallelTrials: 1
    enableTrialEarlyStopping: True
    params:
    # - parameterName: hidden1
    #   type: INTEGER
    #   minValue: 40
    #   maxValue: 400
    #   scaleType: UNIT_LINEAR_SCALE
    - parameterName: LSTM_units_layer1
      type: DISCRETE
      discreteValues:
      - 600
      - 500
      - 400
      - 300
      
    - parameterName: LSTM_units_layer2
      type: DISCRETE
      discreteValues:
      - 600
      - 500
      - 400
      - 300

    - parameterName: LSTM_units_layer2
        type: DISCRETE
        discreteValues:
        - 600
        - 500
        - 400
        - 300

    - parameterName: LSTM_units_layer2
      type: CATEGORICAL
      categoricalValues:
      - BasicLSTMCell
      - BasicRNNCell
      - GRUCell
      - LSTMCell
      - LayerNormBasicLSTMCell

    - parameterName: Dropout
        type: DISCRETE
        discreteValues:
          - 0.25
          - 0.5
          - 0.75

    - parameterName: Optimizer
      type: CATEGORICAL
      categoricalValues:
      - adam
      - sgd
      - rms
      - adagrad
      - adamax
